
# FROM node:alpine

# ENV NODE_ENV=production

# WORKDIR /app

# COPY ["package.json", "package-lock.json*", "./"]

# RUN npm install --production

# COPY . .
# EXPOSE 5000


# CMD [ "npm", "start" ]

# build environment
FROM node:12.18.2-alpine

RUN mkdir /webReact

WORKDIR  /webReact

# install app dependencies
COPY package.json .
# COPY package-lock.json .

RUN npm install

COPY . .

EXPOSE 3000


CMD [ "npm", "run", "start"]
